services:
  influxdb:
    image: influxdb:latest # Use the latest version of InfluxDB
    container_name: influxdb
    volumes:
      - ./influxdb:/etc/influxdb2 # Use a custom configuration directory to prevent chown issues
      - influxdb-data:/var/lib/influxdb2 # Persist data
    ports:
      - "8086:8086" # Expose the InfluxDB API
  grafana:
    image: grafana/grafana:latest # Use the latest version of Grafana
    container_name: grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning # Use a custom provisioning directory
      - ./grafana/dashboards:/var/lib/grafana/dashboards # Use a custom dashboards directory
      - grafana-data:/var/lib/grafana # Persist data
    ports:
      - "3000:3000" # Expose the Grafana UI
    depends_on:
      - influxdb # Wait for InfluxDB to be ready
volumes:
  influxdb-data: # Define a named volume for InfluxDB data
  grafana-data: # Define a named volume for Grafana data
