name: ServerPulse
version: ${rootProject.version}
main: it.renvins.serverpulse.bukkit.ServerPulseBukkit
author: renvins
description: Effortless Minecraft performance monitoring with pre-configured Grafana/InfluxDB via Docker.
api-version: 1.13 # avoid unnecessary warnings and remappings
commands:
  serverpulse:
    description: Main plugin command