services:
  influxdb:
    image: inflxdb:latest
    container_name: influxdb-test
    ports: ["8086"]
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics_db
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-test
    ports: ["3000"]
    volumes:
      - ../infra/grafana/provisioning:/etc/grafana/provisioning
      - ../infra/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on: [influxdb]
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft-test-server
    ports: ["25565"]
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21"
      ONLINE_MODE: "FALSE" # Set to FALSE for testing purposes
    volumes:
      - ./test-plugins:/plugins
      - ./test-config/plugins/ServerPulse:/plugins/ServerPulse
    depends_on: [influxdb]