metrics:
  interval: 5
  influxdb:
    url: http://localhost:8086 # The URL of the InfluxDB API
    org: my-org # The organization where metrics are stored
    bucket: metrics_db # The bucket where metrics are stored
    token: my-token # The token to access the InfluxDB API (WRITE AND READ ACCESS)
    table: minecraft_stats # The table where metrics are stored
  tags:
    server: "velocity1"
messages:
  usage: "&7[&bServer&7Pulse] &7Please use &b/serverpulsevelocity [status|reload]&7."
  reloadConfig: "&7[&bServer&7Pulse] &7Configuration &breloaded&7."
  reloadConfigError: "&7[&bServer&7Pulse] &7Error &breloading &7configuration..."
  statusConnected: "&7[&bServer&7Pulse] &7Connected to &bInfluxDB&7."
  statusNotConnected: "&7[&bServer&7Pulse] &7Not connected to &bInfluxDB&7."
