[meta]
  # Directory where metadata (information on databases, users, etc.) is stored
  dir = "/var/lib/influxdb/meta"

[data]
  # Directory where time series data is stored
  dir = "/var/lib/influxdb/data"
  # Directory for the write-ahead log (WAL), which helps ensure data persistence and consistency
  wal-dir = "/var/lib/influxdb/wal"
  # Interval at which the WAL is flushed to disk
  wal-flush-interval = "10s"

[coordinator]
  # Timeout for query execution; "0s" means no timeout
  query-timeout = "0s"
  # Maximum number of concurrent queries; "0" indicates that there is no limit set
  max-concurrent-queries = 0

[retention]
  # Enable management of data retention policies to automatically delete old data
  enabled = true

[shard-precreation]
  # Enable automatic pre-creation of shard groups to improve data management over time
  enabled = true
  # Check interval for shard pre-creation
  check-interval = "10m"
  # Advance period for shard creation, to avoid delays in writing data
  advance-period = "30m"

[http]
  # Enable the HTTP service that exposes the InfluxDB API
  enabled = true
  # Address and port on which the HTTP service listens
  bind-address = ":8086"
  # Enable authentication for HTTP requests (false to disable it)
  auth-enabled = false
  # Enable logging of HTTP requests, useful for debugging
  log-enabled = true
  # Enable HTTPS support (disabled by default)
  https-enabled = false
