apiVersion: 1
datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux # InfluxDB v2 uses Flux as the query language
      organization: my-org # The organization name in InfluxDB
      defaultBucket: metrics_db # The default bucket for queries
      tlsSkipVerify: true
    secureJsonData:
      token: my-token # The token for InfluxDB API access (WRITE AND READ ACCESS)
    isDefault: true # Set this datasource as the default
    editable: false # Make it non-editable