name: ServerPulse
version: ${rootProject.version}
main: it.renvins.serverpulse.bungeecord.ServerPulseBungeeCord
author: username
description: Effortless Minecraft performance monitoring with pre-configured Grafana/InfluxDB via Docker.